LIB 26 y LIB 27
RAParra515/networkChargingTariff pull request #11
Opened 2023-10-03 13:32 UTC by AlonsoDachser

LIB 26 y LIB 27

2023-10-03 14:04 UTC, ronald-pacheco-dchs requested changes

2023-10-03 14:04 UTC, ronald-pacheco-dchs commented on src/main/java/com/dachser/api/services/LocalChargesService.java
Se tiene que refactorizar este trozo de código:
No tenemos que hacer la búsqueda por el IdCompuesto si no por el uuid (Que ya se esta haciendo en la línea 144 con el `findByUuid`).
Con la entidad que nos va a devolver el `findByUuid `vamos a realizar el update.
**_Esto lo vamos a revisar juntos, me avisas cuando tengas tiempo._**

2023-10-03 14:04 UTC, ronald-pacheco-dchs commented on src/main/java/com/dachser/api/entities/id/LocalChargesId.java
> +
falta la el atributo de `valid`

2023-10-03 14:04 UTC, ronald-pacheco-dchs commented on src/main/resources/Data.sql
> +ALTER TABLE LOCAL_CHARGES ADD PRIMARY KEY (ID_01_MODE, ID_02_COUNTRY,ID_03_AIRPORT,ID_06_CHARGE_CODE,ID_05_CHARGE_TYPE,ID_04_CURRENCY);
Agregar la columna `ACTIVE_FLAG`

2023-10-03 14:09 UTC, AlonsoDachser commented on src/main/java/com/dachser/api/services/LocalChargesService.java
> +
done

2023-10-05 07:47 UTC, ronald-pacheco-dchs approved these changes

2023-10-05 07:47 UTC, merged